### ISSUE TITLE
window.molpay.startMolpay is not a function

### ISSUE THREAD

**Issue by ladaniavadh** [RazerMS/rms-mobile-xdk-cordova#9]
Hii,
I have followed till step-4 for the installation, after run the project i can't see anything on html

Please help me with this

**Comment by hisyamadzha** [comment]
> Hii,
> I have followed till step-4 for the installation, after run the project i can't see anything on html
> 
> Please help me with this
Try to delete the folder 'plugins' and adding back the plugin by run this command 'cordova plugin add molpay-mobile-xdk-cordova'

**Comment by ladaniavadh** [comment]
I have tried this but It is not working 
getting the same error
![error](https://user-images.githubusercontent.com/30779077/79716009-f86fe280-82f2-11ea-8265-6301d9bba47b.PNG)

**Comment by hisyamadzha** [comment]
> I have tried this but It is not working
> getting the same error
> ![error](https://user-images.githubusercontent.com/30779077/79716009-f86fe280-82f2-11ea-8265-6301d9bba47b.PNG)

Check whether it exist in node_modules folder. If not in there, try delete node_modules folder and run 'npm install'

**Comment by ladaniavadh** [comment]
![Screenshot (54)](https://user-images.githubusercontent.com/30779077/79727737-755a8680-830a-11ea-8b2e-307217a296b1.png)
Yes it is available in node_modules folder, also try with delete modules and install it again
Facing the same issue

**Comment by trantienit2015** [comment]
I also had this problem. Has anyone solved it yet?

**Comment by hisyamadzha** [comment]
Hi @trantienit2015, this issue raised by @ladaniavadh while his trying to import this package into Ionic 4. So, I already create a sample project to refer [https://github.com/RazerMS/rms-mobile-xdk-examples/tree/ionic4/Ionic4]

**Comment by trantienit2015** [comment]
Thank you so much.

Vào Th 6, 24 thg 4, 2020 lúc 12:00 hisyamadzha <notifications@github.com>
đã viết:
